-- MySQL Script generated by MySQL Workbench
-- Wed Sep 18 15:53:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema flight_res
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Flight` (
  `flight_id` INT NOT NULL AUTO_INCREMENT,
  `flight_name` VARCHAR(45) NOT NULL,
  `seating_capacity` INT NOT NULL,
  `reservation_capacity` INT NOT NULL,
  PRIMARY KEY (`flight_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flight_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`flight_schedule` (
  `Flight_flight_id` INT NOT NULL,
  `schedule_day` DATE NOT NULL,
  PRIMARY KEY (`Flight_flight_id`),
  INDEX `fk_Flight_has_Route_Flight_idx` (`Flight_flight_id` ASC) VISIBLE,
  CONSTRAINT `fk_Flight_has_Route_Flight`
    FOREIGN KEY (`Flight_flight_id`)
    REFERENCES `mydb`.`Flight` (`flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Route` (
  `route_id` INT NOT NULL AUTO_INCREMENT,
  `source` VARCHAR(45) NOT NULL,
  `destination` VARCHAR(45) NOT NULL,
  `distance` FLOAT NOT NULL,
  `duration` INT NOT NULL,
  `flight_schedule_Flight_flight_id` INT NOT NULL,
  PRIMARY KEY (`route_id`, `flight_schedule_Flight_flight_id`),
  INDEX `fk_Route_flight_schedule1_idx` (`flight_schedule_Flight_flight_id` ASC) VISIBLE,
  CONSTRAINT `fk_Route_flight_schedule1`
    FOREIGN KEY (`flight_schedule_Flight_flight_id`)
    REFERENCES `mydb`.`flight_schedule` (`Flight_flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Schedule_Day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Schedule_Day` (
  `schedule_days_id` INT NOT NULL AUTO_INCREMENT,
  `day` DATE NOT NULL,
  PRIMARY KEY (`schedule_days_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passenger` (
  `passenger_id` INT NOT NULL AUTO_INCREMENT,
  `passenger_name` VARCHAR(45) NOT NULL,
  `passenger_age` INT NOT NULL,
  `passenger_gender` VARCHAR(45) NOT NULL,
  `passenger_seat_no` INT NOT NULL,
  `booking_date` DATE NOT NULL,
  `Flight_flight_id` INT NOT NULL,
  PRIMARY KEY (`passenger_id`, `Flight_flight_id`),
  INDEX `fk_Passenger_Flight1_idx` (`Flight_flight_id` ASC) VISIBLE,
  CONSTRAINT `fk_Passenger_Flight1`
    FOREIGN KEY (`Flight_flight_id`)
    REFERENCES `mydb`.`Flight` (`flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Credential`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Credential` (
  `user_credentials_id` INT NOT NULL AUTO_INCREMENT,
  `user_type` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `login_status` TINYINT NOT NULL,
  PRIMARY KEY (`user_credentials_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User_Profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User_Profile` (
  `user_profile_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `mobile_number` VARCHAR(45) NOT NULL,
  `email_id` VARCHAR(45) NOT NULL,
  `User_Credential_user_credentials_id` INT NOT NULL,
  PRIMARY KEY (`user_profile_id`, `User_Credential_user_credentials_id`),
  INDEX `fk_User_Profile_User_Credential1_idx` (`User_Credential_user_credentials_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Profile_User_Credential1`
    FOREIGN KEY (`User_Credential_user_credentials_id`)
    REFERENCES `mydb`.`User_Credential` (`user_credentials_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`passenger_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`passenger_schedule` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT,
  `journey_date` DATETIME NOT NULL,
  `source` VARCHAR(45) NOT NULL,
  `destination` VARCHAR(45) NOT NULL,
  `reservation_type` VARCHAR(45) NOT NULL,
  `Passenger_passenger_id` INT NOT NULL,
  `Passenger_Flight_flight_id` INT NOT NULL,
  PRIMARY KEY (`schedule_id`, `Passenger_passenger_id`, `Passenger_Flight_flight_id`),
  INDEX `fk_Schedule_Passenger1_idx` (`Passenger_passenger_id` ASC, `Passenger_Flight_flight_id` ASC) VISIBLE,
  CONSTRAINT `fk_Schedule_Passenger1`
    FOREIGN KEY (`Passenger_passenger_id` , `Passenger_Flight_flight_id`)
    REFERENCES `mydb`.`Passenger` (`passenger_id` , `Flight_flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation` (
  `reservation_id` INT NOT NULL AUTO_INCREMENT,
  `journey_date` DATE NOT NULL,
  `no_of_seats` INT NOT NULL,
  `User_Profile_user_profile_id` INT NOT NULL,
  `User_Profile_User_Credential_user_credentials_id` INT NOT NULL,
  PRIMARY KEY (`reservation_id`, `User_Profile_user_profile_id`, `User_Profile_User_Credential_user_credentials_id`),
  INDEX `fk_Reservation_User_Profile1_idx` (`User_Profile_user_profile_id` ASC, `User_Profile_User_Credential_user_credentials_id` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_User_Profile1`
    FOREIGN KEY (`User_Profile_user_profile_id` , `User_Profile_User_Credential_user_credentials_id`)
    REFERENCES `mydb`.`User_Profile` (`user_profile_id` , `User_Credential_user_credentials_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `Schedule_schedule_id` INT NOT NULL,
  `payment_info` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Schedule_schedule_id`),
  INDEX `fk_Schedule_has_Passenger_Detail_Schedule1_idx` (`Schedule_schedule_id` ASC) VISIBLE,
  CONSTRAINT `fk_Schedule_has_Passenger_Detail_Schedule1`
    FOREIGN KEY (`Schedule_schedule_id`)
    REFERENCES `mydb`.`passenger_schedule` (`schedule_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation_has_Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation_has_Flight` (
  `Reservation_reservation_id` INT NOT NULL,
  `Reservation_User_Profile_user_profile_id` INT NOT NULL,
  `Reservation_User_Profile_User_Credential_user_credentials_id` INT NOT NULL,
  `Flight_flight_id` INT NOT NULL,
  PRIMARY KEY (`Reservation_reservation_id`, `Reservation_User_Profile_user_profile_id`, `Reservation_User_Profile_User_Credential_user_credentials_id`, `Flight_flight_id`),
  INDEX `fk_Reservation_has_Flight_Flight1_idx` (`Flight_flight_id` ASC) VISIBLE,
  INDEX `fk_Reservation_has_Flight_Reservation1_idx` (`Reservation_reservation_id` ASC, `Reservation_User_Profile_user_profile_id` ASC, `Reservation_User_Profile_User_Credential_user_credentials_id` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_has_Flight_Reservation1`
    FOREIGN KEY (`Reservation_reservation_id` , `Reservation_User_Profile_user_profile_id` , `Reservation_User_Profile_User_Credential_user_credentials_id`)
    REFERENCES `mydb`.`Reservation` (`reservation_id` , `User_Profile_user_profile_id` , `User_Profile_User_Credential_user_credentials_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_has_Flight_Flight1`
    FOREIGN KEY (`Flight_flight_id`)
    REFERENCES `mydb`.`Flight` (`flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
